### ISSUE TITLE
デスクトップ・タブレットでのレイアウト調整

### ISSUE THREAD

**Issue by komekomeclub5** [komekomeclub5/okiufes2020#1]
CSSでデスクトップとタブレットのコーディングをお願いします。

**Comment by komekomeclub5** [comment]
![1594048553244](https://user-images.githubusercontent.com/56760463/86609642-28bc4880-bfe7-11ea-92db-ac14fad56a8d.jpg)

**Comment by nagii053** [comment]
![image](https://user-images.githubusercontent.com/38526056/86624338-1c8fb580-bffe-11ea-987f-199bc9401da2.png)

**いかがでしょうか**
